# Generated by Django 4.2.20 on 2025-04-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_подтвержден_с_сайта_80_летия_победы'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Подтвержден с сайта 80-летия победы',
            new_name='is_verified',
        ),
    ]
