# Generated by Django 4.2.20 on 2025-04-12 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_подтвержден_с_сайта_80_летия_победы_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=19, unique=True, validators=[django.core.validators.RegexValidator(message='phone number entered in wrong format', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
