# Generated by Django 4.2.20 on 2025-04-12 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_phone_number_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, default='+7999999', max_length=19, null=True, validators=[django.core.validators.RegexValidator(message='phone number entered in wrong format', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together={('email', 'phone_number')},
        ),
    ]
