# Generated by Django 4.2.20 on 2025-04-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Подтвержден с сайта 80-летия победы',
            field=models.BooleanField(default=False),
        ),
    ]
