# Generated by Django 4.2.20 on 2025-04-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='awdawda', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together={('username', 'email', 'phone_number')},
        ),
    ]
