# Generated by Django 4.2.20 on 2025-04-12 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=19, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='phone number entered in wrong format', regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number'),
        ),
    ]
