# Generated by Django 4.2.20 on 2025-04-22 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_customuser_surname_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='surname',
        ),
    ]
