# Generated by Django 4.2.20 on 2025-05-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Дерево', max_length=100)),
                ('content', models.TextField(null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='tree_photos/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
