# Generated by Django 4.2.20 on 2025-04-26 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trees', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trees',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='trees',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trees_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trees',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='tree_photos/'),
        ),
    ]
