# Generated by Django 4.2.20 on 2025-05-11 13:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trees', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trees',
            name='plant_date',
            field=models.DateField(default=datetime.date(2000, 9, 9)),
        ),
        migrations.AlterField(
            model_name='trees',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trees_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TreesImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tree_photos/')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trees.trees', verbose_name='Запрос')),
            ],
        ),
    ]
