# Generated by Django 4.2.20 on 2025-05-11 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_trees_plant_date_alter_trees_owner_treesimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='trees',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
