# Generated by Django 4.2.20 on 2025-05-14 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0004_trees_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trees',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='treesimages',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trees.trees', verbose_name='Дерево'),
        ),
    ]
