# Generated by Django 4.2.20 on 2025-05-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0005_alter_trees_creation_date_alter_treesimages_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='trees',
            name='dedicated_to',
            field=models.CharField(default='', max_length=100),
        ),
    ]
