# Generated by Django 4.2.20 on 2025-04-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trees',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
